# Generated by Django 4.2.5 on 2023-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_category',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
